version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - notes

  auth:
    build:
      context: ./auth
    ports:
      - "8001:8001"

  notes:
    build:
      context: ./notes
    ports:
      - "8002:8002"
